# Generated by Django 5.2 on 2025-05-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
