# Generated by Django 5.2 on 2025-05-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('host', 'Host')], default='student', max_length=10),
        ),
    ]
